/*
Write a program that computes a ”walk” (of a cute robot) across a 10x10 array. The array contains characters (all initially ’.’). The user can enter four different directions north, east, south, west, by entering the characters n,e,s,w to control the walk. If the user enters x the program exits. After each direction-command the array is printed with the walk being display by capital letter starting with A to Z. We use A for the starting point, with 25 remaining letters to denote the steps. After having used letter Z to denote a step, we wrap around and start again with A. To make the walk more interesting, the user is not allowed to revisit a location. In this case the program does not print the array, but prints ”You cannot go there!” - Yes, you can trap yourself.

Starting in the upper left corner (position 0,0):
% u6_walker
A.........
..........
..........
..........
..........
..........
..........
..........
..........
..........
Enter direction command: n

You cannot go there!
Enter direction command: s

A.........
B.........
..........
..........
..........
..........
..........
..........
..........
..........
Enter direction command: e

A.........
BC........
..........
..........
..........
..........
..........
..........
..........
..........
Enter direction command: w

You cannot go there!
Enter direction command: s

A.........
BC........
.D........
..........
..........
..........
..........
..........
..........
..........
Enter direction command: x

%
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {

    return 0;
}
